#!/usr/bin/env nextflow
nextflow.enable.dsl=2

process bbmerge{
    //conda "/gpfs/projects/bgmp/shared/groups/2025/chimera/envs/getBarcodes" --new bbtools version
    conda "/gpfs/projects/bgmp/shared/groups/2025/chimera/envs/old_bbmerge" // --old bbtools version
    input:
        tuple val(sampleId), path(read1), path(read2)

    output:
        path "${sampleId}.merged.fastq.gz"

    publishDir "/projects/bgmp/shared/groups/2025/chimera/mlscha/bgmp-2025-chimera-fixed/110625_shortdata/01-bbmerge_out/", mode: 'copy' 

    script:
    """
    /usr/bin/time -v /gpfs/projects/bgmp/shared/groups/2025/chimera/envs/old_bbmerge/bbtools/lib/bbmerge.sh \
    in1=${read1}\
    in2=${read2}\
    out=${sampleId}.merged.fastq.gz \
    outu1=/projects/bgmp/shared/groups/2025/chimera/mlscha/bgmp-2025-chimera-fixed/110625_shortdata/01-bbmerge_out/${sampleId}_R1.unmerged.fastq.gz \
    outu2=/projects/bgmp/shared/groups/2025/chimera/mlscha/bgmp-2025-chimera-fixed/110625_shortdata/01-bbmerge_out/${sampleId}_R2.unmerged.fastq.gz\
    ihist=/projects/bgmp/shared/groups/2025/chimera/mlscha/bgmp-2025-chimera-fixed/110625_shortdata/01-bbmerge_out/${sampleId}.bbmerge.stats.txt
    """
}

process hts_primers{
    //conda "/gpfs/projects/bgmp/shared/groups/2025/chimera/envs/getBarcodes"
    conda "/gpfs/projects/bgmp/shared/groups/2025/chimera/envs/Illumina_env"
    input:
        path merged_file
    output:
        path "${merged_file.simpleName}.flip.trim_SE.fastq.gz"
    
    publishDir "/projects/bgmp/shared/groups/2025/chimera/mlscha/bgmp-2025-chimera-fixed/110625_shortdata/02-hts_primers_out/", mode: 'copy' //try move?

    script:
    //mkdir -p initializes the directory since just outputting the .stats.txt file is not enough to also make the directory
    """
    mkdir -p /projects/bgmp/shared/groups/2025/chimera/mlscha/bgmp-2025-chimera-fixed/110625_shortdata/02-hts_primers_out/
    /usr/bin/time -v hts_Primers -U ${merged_file} -f ${merged_file.simpleName}.flip.trim \
    -P /projects/bgmp/shared/groups/2025/chimera/mlscha/bgmp-2025-chimera-fixed/stubby_adapters/HK_ABC-stub_FWD.fasta \
    -Q /projects/bgmp/shared/groups/2025/chimera/mlscha/bgmp-2025-chimera-fixed/stubby_adapters/HK_ABC-stub_REV.fasta \
    -l 5 -x -e 6 -d 6 \
    -L /projects/bgmp/shared/groups/2025/chimera/mlscha/bgmp-2025-chimera-fixed/110625_shortdata/02-hts_primers_out/${merged_file.simpleName}.flip.stats.txt -F
    """
}

process make_barcode_fasta {
    input:
        path trimmed_file
    output:
        path "${trimmed_file.simpleName}.cut.txt"

    publishDir "/projects/bgmp/shared/groups/2025/chimera/mlscha/bgmp-2025-chimera-fixed/110625_shortdata/03-make_barcode_fasta_out/", mode: 'copy'

    script:
    //changed the "20" to "24" when running our data
    """
    /usr/bin/time -v gzip -cd ${trimmed_file} \
    | awk 'NR%4 ==2' | cut -c1-24 | awk 'BEGIN{FIELDWIDTHS="24"} {print \$1}' > ${trimmed_file.simpleName}.cut.txt 
    """
}

process count_barcodes{
    input:
        path barcode_file
    output:
        path "${barcode_file.simpleName}.count.txt"
    publishDir "/projects/bgmp/shared/groups/2025/chimera/mlscha/bgmp-2025-chimera-fixed/110625_shortdata/04-count_barcodes_out/", mode: 'copy'

    script:
    //added grep command to remove empty lines before unique counting
    //this should remove "empty" barcode counts that are generated by unique
    //this could be parallelized further later with find and xargs, but it means making a file or a temp file
    """
    /usr/bin/time -v cat ${barcode_file} | sort -T ./ --parallel=40 | grep -v "^\$" | uniq -c | \
    awk '{print \$2 "\t" \$1}' > ${barcode_file.simpleName}.count.txt
    """
}

process star_code{
    conda "/projects/bgmp/shared/groups/2025/chimera/envs/starcode_env"
    input:
        path count_file

    output:
        path "${count_file.simpleName}.collapse.d1.tsv"
    
    publishDir "/projects/bgmp/shared/groups/2025/chimera/mlscha/bgmp-2025-chimera-fixed/110625_shortdata/05-starcode_out", mode: 'copy'
    
    script:
    """
    /usr/bin/time -v starcode -d1 --sphere -i ${count_file} --output "${count_file.simpleName}.collapse.d1.tsv" --print-clusters
    """
}

workflow {
    // Create channels for paired reads
    read_pairs = Channel
        .fromFilePairs('/projects/bgmp/shared/groups/2025/chimera/mlscha/bgmp-2025-chimera-fixed/ShortIlluminaData/*{R1,R2}_001.fastq')
        .map { sampleId, reads -> tuple(sampleId, reads[0], reads[1]) }
        read_pairs.view()
    bbmerge(read_pairs)

    //  //collect the "output" file paths (only the merged file)
    merged_files = bbmerge.out
    merged_files.view()

    //run HTS Primers
    hts_primers(merged_files)

    trimmed_file = hts_primers.out
    //make the fasta file with all barcodes
    make_barcode_fasta(trimmed_file)

    //grab barcode file
    barcode_file = make_barcode_fasta.out

    //count barcodes from barcode file
    count_barcodes(barcode_file)

    //grab counted barcode file
    count_file = count_barcodes.out
    star_code(count_file)
}