#!/bin/bash
#SBATCH --account=bgmp
#SBATCH --partition=bgmp
#SBATCH --mem=32GB
#SBATCH --job-name=pacbio
#SBATCH --out=/projects/bgmp/shared/groups/2025/chimera/jonat/original_pacbio_pipeline/results/slurm/slurm-%j.out
#SBATCH --err=/projects/bgmp/shared/groups/2025/chimera/jonat/original_pacbio_pipeline/results/slurm/slurm-%j.err

input_file="/projects/bgmp/shared/groups/2025/chimera/jonat/original_pacbio_pipeline/input_files/test.bam"
output_dir="/projects/bgmp/shared/groups/2025/chimera/jonat/original_pacbio_pipeline/results/"

run_iter_num=$(ls -1 -d $output_dir/*/ | sed -r 's/.+_(.+)\//\1/' | sort -n | awk '{num=$1} END{print num+1}')
results_dir="${output_dir}/results_${run_iter_num}"
input_file_basename=$(basename $input_file .bam)

envs_dir="/projects/bgmp/shared/groups/2025/chimera/envs"

tmp_dir_root=$(mktemp -d)


# Step 1: Convert from BAM to FASTQ
tmp_dir_bedtools="${tmp_dir_root}/01_bedtools/"
bedtools_output="${tmp_dir_bedtools}/${input_file_basename}.fastq"
mamba run -p "${envs_dir}/bedtools" /usr/bin/time -v bamtofastq \
    -i $input_file \
    -fq $bedtools_output
gzip $bedtools_output
cp $tmp_dir_bedtools $results_dir


# Step 2: Extract barcodes and sequences
tmp_dir_extract_seqs="${tmp_dir_root}/02_extract_seqs/"
# This file is specified on the command line
extract_seqs_fasta_output="${tmp_dir_extract_seqs}/${input_file_basename}.fasta"
# This file is generated by the script as a side effect
extract_seqs_tsv_output="${tmp_dir_extract_seqs}/${input_file_basename}bc_stats_for_starcode.tsv"
mamba run -p "${envs_dir}/biopython" /usr/bin/time -v python /projects/bgmp/shared/groups/2025/chimera/jonat/original_pacbio_pipeline/barcode_extract_v9_no_coll_noEnvZ_HK_MP.py \
    -i $bedtools_output \
    -o $extract_seqs_output
cp $tmp_dir_extract_seqs $results_dir


# Step 3: Run Starcode
tmp_dir_starcode="${tmp_dir_root}/03_starcode/"
starcode_output="${tmp_dir_starcode}/${input_file_basename}.tsv"
mamba run -p "${envs_dir}/starcode" /usr/bin/time -v starcode \
    -d1 \
    --sphere \
    --print-clusters \
    -i $extract_seqs_tsv_output \
    --output $starcode_output
cp $tmp_dir_starcode $results_dir


# Step 4: Call consensus

exit
